---
title: "Breaking Bad"
author: "Maciek Staniszewski"
date: "4/13/2023"
format: html
execute:
  echo: fenced
---

# ASSIGNMENT

Pick a TV show that had its premieres on TV and thus has some viewership numbers reported on Wikipedia. E.g. [Suits](https://en.wikipedia.org/wiki/List_of_Suits_episodes) (see table just above the References)

Then create a short report (you can copy the content from Wikipedia or other pages for this task) that contains, for example:

(do a commit after each step!)

1.  A brief description of the show (use *italics* for names).
2.  A photo with the logo or a shot from the show itself.
3.  A summary of some basic statistics (e.g. on viewership or ratings).
4.  A graph of the viewership over time.
5.  A graph of the episode-to-episode (or season-to-season) changes in viewership.
6.  A short description of the observed changes that includes inline references to numbers (e.g. the viewership decreased by `insert_calculated_number` between seasons 3 and 5).
7.  Make sure your report looks nice -\> this time we're mostly interested in the output and not necessarily the codes used to achieve it.
8.  `render` your report and save it in the relevant folder of your repo.
9.  Commit the changes and push them to Github.

# Breaking Bad

*Breaking Bad* is an American neo-Western crime drama television series created and produced by Vince Gilligan for AMC. Set and filmed in **Albuquerque, New Mexico**, the series follows Walter White (Bryan Cranston), an underpaid, overqualified, and dispirited high-school chemistry teacher who is struggling with a recent diagnosis of stage-three lung cancer. 
