---
title: "Assignment - Metaanalysis"
author: "Dustin Pacholleck"
date: today
format:  
  html:
    theme: lumen
    toc: true
    toc_float: true
title-block-banner: true
execute:
  echo: fenced
---
```{r}
#| label = "setup",
#| include = FALSE
library(meta)
library(metafor)
library(dplyr)
# install.packages("openxlsx")
library(openxlsx)
setwd("C:/Users/duzzi/Desktop/Reproductible Research/RRcourse2023/13. Metaanalysis")
```

## Assignment 
Import the data

```{r}
Meta_Analysis_Data = read.xlsx("data\\metaanalysis_data.xlsx")
```

### combine the effects
```{r}
Meta_Analysis_Data$male_share <- Meta_Analysis_Data$Male.authors/(Meta_Analysis_Data$Female.authors+Meta_Analysis_Data$Male.authors)

m.boys <- metacont(n.e=Meta_Analysis_Data$N_boys,
                  mean.e=Meta_Analysis_Data$Mean_boys_play_male,
                  sd.e=Meta_Analysis_Data$SD_boys_play_male,
                  n.c=Meta_Analysis_Data$N_boys,
                  mean.c=Meta_Analysis_Data$Mean_boys_play_female,
                  sd.c=Meta_Analysis_Data$SD_boys_play_female,
                  data=Meta_Analysis_Data,
                  studlab=paste(Study),
                  comb.fixed = TRUE,
                  comb.random = TRUE,
)
m.boys


m.girls <- metacont(n.e=Meta_Analysis_Data$N_girls,
                  mean.e=Meta_Analysis_Data$Mean_girls_play_male,
                  sd.e=Meta_Analysis_Data$SD_girls_play_male,
                  n.c=Meta_Analysis_Data$N_girls,
                  mean.c=Meta_Analysis_Data$Mean_girls_play_female,
                  sd.c=Meta_Analysis_Data$SD_girls_play_female,
                  data=Meta_Analysis_Data,
                  studlab=paste(Study),
                  comb.fixed = TRUE,
                  comb.random = TRUE,
)
m.girls

```
#### create a funnel plot (what do you see?)
```{r}

forest(m.boys)

contour_levels <- c(0.90, 0.95, 0.99)
contour_colors <- c("darkblue", "blue", "lightblue")
funnel(m.boys, contour = contour_levels, col.contour = contour_colors)
legend("topright", c("p < 0.10", "p < 0.05", "p < 0.01"), bty = "n", fill = contour_colors)

contour_levels <- c(0.90, 0.95, 0.99)
contour_colors <- c("darkblue", "blue", "lightblue")
funnel(m.girls, contour = contour_levels, col.contour = contour_colors)
legend("topright", c("p < 0.10", "p < 0.05", "p < 0.01"), bty = "n", fill = contour_colors)
```
#### check if methods / quality affect the results
```{r}


metareg(m.boys, "Parent.present" + "Country" + "Year" + "male_share") 
```

#### does author gender affect it?
