---
title: "Metaanalysis ex"
author: "Artur Skowroński"
date: "2023-06-15"
output: html_document
---
```{r label = "setup", include = FALSE}
library(meta)
library(metafor)
library(dplyr)
library(readxl)
data <- read_excel("data/metaanalysis_data.xlsx")

```

```{r}
men <- metacont(n.e=N_boys,
                      mean.e=Mean_boys_play_male,
                      sd.e=SD_boys_play_male,
                      n.c=N_boys,
                      mean.c=Mean_boys_play_female,
                      sd.c=SD_boys_play_female,
                      data=data,
                      studlab=paste(Study),
                      comb.fixed = TRUE,
                      comb.random = TRUE,
)

men
```

```{r}
women <- metacont(n.e=N_girls,
                       mean.e=Mean_girls_play_male,
                       sd.e=SD_girls_play_male,
                       n.c=N_girls,
                       mean.c=Mean_girls_play_female,
                       sd.c=SD_girls_play_female,
                       data=data,
                       studlab=paste(Study),
                       comb.fixed = TRUE,
                       comb.random = TRUE,
)

women
```
```{r}
contour_levels <- c(0.90, 0.95, 0.99)
contour_colors <- c("darkblue", "blue", "lightblue")
funnel(men, contour = contour_levels, col.contour = contour_colors)
legend("topright", c("p < 0.10", "p < 0.05", "p < 0.01"), bty = "n", fill = contour_colors)
```
```{r}
contour_levels <- c(0.90, 0.95, 0.99)
contour_colors <- c("darkblue", "blue", "lightblue")
funnel(women, contour = contour_levels, col.contour = contour_colors)
legend("topright", c("p < 0.10", "p < 0.05", "p < 0.01"), bty = "n", fill = contour_colors)
```

```{r}
men %>% metareg(~ `Female authors` + `Male authors`)
```
```{r}
women %>% metareg(~ `Female authors` + `Male authors`)
```