<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="TingWei">

<title>metaanalysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="assignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment_files/libs/quarto-html/quarto.js"></script>
<script src="assignment_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">metaanalysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>TingWei </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="sex-differences-in-childrens-toy-preferences" class="level2">
<h2 class="anchored" data-anchor-id="sex-differences-in-childrens-toy-preferences">Sex differences in children’s toy preferences</h2>
<p>Neutral toys (1 = neutral toys included; 2 = neutral toys not included); Parent present (1 = absent; 2 = minimal interaction; 3 = moderate or full interaction); Setting = location of study (1 = home; 2 = laboratory; 3 = nursery); Country = gender inequality index, a measure of how gender egalitarian the country was at the time the study took place.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("openxlsx")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages('metafor')</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages('meta')</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 程辑包'metafor'是用R版本4.2.3 来建造的</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>载入需要的程辑包：Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>载入需要的程辑包：metadat</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 程辑包'metadat'是用R版本4.2.3 来建造的</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>载入需要的程辑包：numDeriv</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Loading the 'metafor' package (version 4.2-0). For an
introduction to the package please type: help(metafor)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openxlsx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 程辑包'openxlsx'是用R版本4.2.3 来建造的</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(meta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 程辑包'meta'是用R版本4.2.3 来建造的</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading 'meta' package (version 6.2-1).
Type 'help(meta)' for a brief overview.
Readers of 'Meta-Analysis with R (Use R!)' should install
older version of 'meta' package: https://tinyurl.com/dt4y5drs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/metacont.RData"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>data<span class="ot">=</span><span class="fu">read.xlsx</span>(<span class="st">"data/metaanalysis_data.xlsx"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   27 obs. of  28 variables:
 $ Study                                    : chr  "Alexander &amp; Saenz (2012)" "Arthur (2014)" "Berenbaum &amp; Hines (1992)" "Berenbaum &amp; Snyder (1995)" ...
 $ Female.authors                           : num  2 1 2 2 1 2 5 2 3 3 ...
 $ Male.authors                             : num  0 0 0 0 3 1 1 0 3 3 ...
 $ Age.(months)                             : num  19.5 19 65.8 93.1 87 ...
 $ N_boys                                   : num  47 22 18 19 15 10 21 38 12 25 ...
 $ N_girls                                  : num  47 18 18 19 15 10 21 38 12 25 ...
 $ Mean_boys_play_male                      : num  439 148 325 484 260 ...
 $ SD_boys_play_male                        : num  166.1 105 270.2 141.3 67.7 ...
 $ Mean_girls_play_male                     : num  248.6 54 135.1 202.5 98.4 ...
 $ SD_girls_play_male                       : num  161 53 202 168 101 ...
 $ Mean_boys_play_female                    : num  377.3 126 33.5 26.4 7.2 ...
 $ SD_boys_play_female                      : num  170.9 67 69.5 92 21.5 ...
 $ Mean_girls_play_female                   : num  539 244 248 265 145 ...
 $ SD_girls_play_female                     : num  214 54 246 241 110 ...
 $ Neutral.toys                             : num  1 0 1 1 1 1 1 1 1 1 ...
 $ Year                                     : num  2012 2014 1992 1995 1989 ...
 $ Parent.present                           : num  3 2 2 2 1 3 2 1 3 3 ...
 $ Setting                                  : num  2 2 2 1 2 3 2 1 2 2 ...
 $ Country                                  : num  0.256 0.28 0.252 0.252 0.141 0.141 0.248 NA 0.228 0.228 ...
 $ Case.definition.adequate                 : chr  "*" "*" "X" "*" ...
 $ Representativeness.of.cases              : chr  "*" "X" "*" "X" ...
 $ Selection.of.controls                    : chr  "X" "X" "*" "*" ...
 $ Parental.opinion                         : chr  "X" "X" "*" "*" ...
 $ Comparability.of.both.groups             : chr  "*" "**" "*" "*" ...
 $ Ascertainment.of.behaviour               : chr  "*" "*" "*" "*" ...
 $ Same.ascertainment.method.for.both.groups: chr  "*" "*" "*" "*" ...
 $ Non‐response.rate                        : chr  "X" "*" "X" "*" ...
 $ NOS.score                                : num  5 6 6 7 6 8 7 6 7 7 ...</code></pre>
</div>
</div>
<section id="compare-boy-and-girl-play-malestoy." class="level3">
<h3 class="anchored" data-anchor-id="compare-boy-and-girl-play-malestoy.">Compare boy and girl play males’toy.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>m.raw <span class="ot">&lt;-</span> <span class="fu">metacont</span>(<span class="at">n.e=</span>N_boys,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mean.e=</span>Mean_boys_play_male,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sd.e=</span>SD_boys_play_male,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">n.c=</span>N_girls,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mean.c=</span>Mean_girls_play_male ,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sd.c=</span>SD_girls_play_male,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data=</span>data,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">studlab=</span><span class="fu">paste</span>(Study),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">comb.fixed =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">comb.random =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>m.raw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of studies combined: k = 27
Number of observations: o = 1610

                          MD              95%-CI     z  p-value
Common effect model  46.8758 [41.2914;  52.4602] 16.45 &lt; 0.0001
Random effects model 94.7832 [66.7897; 122.7766]  6.64 &lt; 0.0001

Quantifying heterogeneity:
 tau^2 = 4678.7733 [2666.5809; 10251.8327]; tau = 68.4016 [51.6389; 101.2513]
 I^2 = 88.0% [83.7%; 91.1%]; H = 2.88 [2.48; 3.36]

Test of heterogeneity:
      Q d.f.  p-value
 216.00   26 &lt; 0.0001

Details on meta-analytical method:
- Inverse variance method
- Restricted maximum-likelihood estimator for tau^2
- Q-Profile method for confidence interval of tau^2 and tau</code></pre>
</div>
</div>
<p>According to the provided results, this is a summary of a meta-analysis. The results show the effect size estimates and confidence intervals for two models, as well as the quantification of heterogeneity and tests of its significance.</p>
<ul>
<li><p>In the Common effect model, the effect size estimate is 46.8758 with a 95% confidence interval of [41.2914; 52.4602]. The corresponding z-value is 16.45, and the p-value is less than 0.0001, indicating a significant effect size.</p></li>
<li><p>In the Random effects model, the effect size estimate is 94.7832 with a 95% confidence interval of [66.7897; 122.7766]. The corresponding z-value is 6.64, and the p-value is less than 0.0001, also indicating a significant effect size.</p></li>
</ul>
<p>The statistics related to heterogeneity are as follows:</p>
<ul>
<li><p>tau^2 represents the estimated variance of heterogeneity, which is 4678.7733 with a 95% confidence interval of [2666.5809; 10251.8327].</p></li>
<li><p>tau represents the estimated standard deviation of heterogeneity, which is 68.4016 with a 95% confidence interval of [51.6389; 101.2513].</p></li>
<li><p>I^2 represents the percentage of heterogeneity, which is 88.0%, indicating substantial heterogeneity.</p></li>
<li><p>H represents the standardized index of heterogeneity, which is 2.88 with a 95% confidence interval of [2.48; 3.36].</p></li>
</ul>
<p>The test of heterogeneity yields the following results:</p>
<ul>
<li>The Q-value is 216.00 with 26 degrees of freedom, and the p-value is less than 0.0001, indicating <strong>significant heterogeneity.</strong></li>
</ul>
</section>
<section id="compare-boy-and-girl-play-femalestoy." class="level3">
<h3 class="anchored" data-anchor-id="compare-boy-and-girl-play-femalestoy.">Compare boy and girl play females’toy.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>m.raw02 <span class="ot">&lt;-</span> <span class="fu">metacont</span>(<span class="at">n.e=</span>N_boys,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mean.e=</span>Mean_boys_play_female,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sd.e=</span>SD_boys_play_female,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">n.c=</span>N_girls,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mean.c=</span>Mean_girls_play_female ,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sd.c=</span>SD_girls_play_female,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data=</span>data,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">studlab=</span><span class="fu">paste</span>(Study),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">comb.fixed =</span> <span class="cn">TRUE</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">comb.random =</span> <span class="cn">TRUE</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>m.raw02</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of studies combined: k = 27
Number of observations: o = 1610

                           MD                95%-CI      z  p-value
Common effect model  -53.5213 [ -59.7585; -47.2841] -16.82 &lt; 0.0001
Random effects model -79.5599 [-101.1964; -57.9233]  -7.21 &lt; 0.0001

Quantifying heterogeneity:
 tau^2 = 2451.0440 [1332.6185; 6488.0519]; tau = 49.5080 [36.5050; 80.5484]
 I^2 = 79.9% [71.4%; 85.9%]; H = 2.23 [1.87; 2.66]

Test of heterogeneity:
      Q d.f.  p-value
 129.28   26 &lt; 0.0001

Details on meta-analytical method:
- Inverse variance method
- Restricted maximum-likelihood estimator for tau^2
- Q-Profile method for confidence interval of tau^2 and tau</code></pre>
</div>
</div>
<p>The test of heterogeneity yields the following results:</p>
<ul>
<li>The Q-value is 129.28 with 26 degrees of freedom, and the p-value is less than 0.001, indicating <strong>significant heterogeneity.</strong></li>
</ul>
<p>So we can see the sex difference in child’s toys preference.</p>
</section>
</section>
<section id="forest-plots-to-see-the-analysis" class="level2">
<h2 class="anchored" data-anchor-id="forest-plots-to-see-the-analysis">Forest plots to see the analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(m.raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(m.raw02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="funnel-plot" class="level2">
<h2 class="anchored" data-anchor-id="funnel-plot">Funnel plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(m.raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(m.raw02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Funnel plot, the distribution of points reveals that some points deviate from the funnel region, indicating <strong>substantial heterogeneity</strong> among the studies. The funnel plot includes two dashed lines: the center line 50 and -50(mean difference), representing the expected effect size. The majority of points are concentrated on one side of the funnel plot, suggesting a tendency towards a particular direction in the study results.</p>
<p>The vertical axis represents the standard error, ranging from 0 to 80, which indicates the precision and reliability of the study results. The horizontal axis represents the mean difference, ranging from -100 to 300. Those with smaller standrd errors and clustered around the center line are considered more reliable. Smaller errors indicate higher accuracy of the study results, and clustering around the center line suggests consistency among these studies. Such studies are deemed more reliable because their results are relatively stable and less influenced by random errors.</p>
</section>
<section id="check-if-author-gender-affect-the-results" class="level2">
<h2 class="anchored" data-anchor-id="check-if-author-gender-affect-the-results">Check if author gender affect the results</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metareg</span>(m.raw,<span class="st">`</span><span class="at">Male.authors</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Female.authors</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 27; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     3978.6644 (SE = 1365.0674)
tau (square root of estimated tau^2 value):             63.0767
I^2 (residual heterogeneity / unaccounted variability): 93.92%
H^2 (unaccounted variability / sampling variability):   16.46
R^2 (amount of heterogeneity accounted for):            14.96%

Test for Residual Heterogeneity:
QE(df = 24) = 193.8118, p-val &lt; .0001

Test of Moderators (coefficients 2:3):
QM(df = 2) = 5.5707, p-val = 0.0617

Model Results:

                estimate       se     zval    pval     ci.lb     ci.ub      
intrcpt         169.8428  40.5086   4.1928  &lt;.0001   90.4474  249.2381  *** 
Male.authors     15.4236  12.9491   1.1911  0.2336   -9.9561   40.8033      
Female.authors  -33.4146  14.5465  -2.2971  0.0216  -61.9252   -4.9040    * 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The findings indicate a high level of residual heterogeneity (I^2 = 93.92%), suggesting significant variability among studies. The model has a relatively low explanatory power (R^2 = 14.96%), indicating that it does not fully account for the observed heterogeneity.</p>
<p>When testing the influence of the moderator variables (male authors and female authors), the results show QM(df = 2) = 5.5707, p-val = 0.0617. Although the p-value is not significant, there might be a trend indicating that the gender of the researchers could have some impact on the effect size.</p>
</section>
<section id="check-if-methods-quality-affect-the-results" class="level2">
<h2 class="anchored" data-anchor-id="check-if-methods-quality-affect-the-results">Check if methods / quality affect the results</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metareg</span>(m.raw,<span class="st">`</span><span class="at">Neutral.toys</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Parent.present</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Setting</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Country</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 1 study with NAs omitted from model fitting.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 26; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     4976.5470 (SE = 1781.9358)
tau (square root of estimated tau^2 value):             70.5446
I^2 (residual heterogeneity / unaccounted variability): 95.14%
H^2 (unaccounted variability / sampling variability):   20.60
R^2 (amount of heterogeneity accounted for):            0.00%

Test for Residual Heterogeneity:
QE(df = 21) = 167.2853, p-val &lt; .0001

Test of Moderators (coefficients 2:5):
QM(df = 4) = 2.9443, p-val = 0.5672

Model Results:

                estimate        se     zval    pval      ci.lb     ci.ub    
intrcpt           1.7425  153.2291   0.0114  0.9909  -298.5809  302.0660    
Neutral.toys     83.7030   52.2421   1.6022  0.1091   -18.6896  186.0956    
Parent.present  -13.2796   25.3704  -0.5234  0.6007   -63.0047   36.4454    
Setting          27.0407   38.1075   0.7096  0.4780   -47.6486  101.7300    
Country          10.7260  234.1139   0.0458  0.9635  -448.1289  469.5809    

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The results show QM(df = 4) = 2.9443, p-val = 0.5672, which does not indicate significant moderating effects of neutral toys, parent presence, setting, and country’s gender inequality index on effect size.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>